### PR TITLE
Add a Wine version chooser

### PR DESCRIPTION
**Pull request by GLolol**
This allows the user to select different Wine paths, such as official Wine and Wine-staging. It defaults to a dynamic search of Wine via `$PATH` lookup, and also allows you to input custom paths. If automatic lookup fails, the script will just exit. Otherwise, the script will ask for input in a loop, repeating if it fails.

winechooser saves its settings to `~/.rlw/wine_choice`, and will run automatically on start if that file doesn't exist. It can also be accessed in the menu via the "Select Wine Version" option.

### Possible TODO

- [ ] Fit in installation instructions somehow... I originally wanted to add comments to each choice (each choice is a large button), but that requires some complex GTK dialogs that a simple radio list / zenity can't handle.

### CODE REVIEW

**Comment by NokiaGuy** [comment]
Clever, some people may have no idea what any of this means though. 

Would $PATH be automatically updated when a new one is installed? For instance, if I installed Wine-Staging **AFTER** normal Wine, would it automatically set it to Wine-Staging?

**Comment by GLolol** [comment]
No. There's no real way of checking which one is /newer/ (any ideas like date-time checking are stupid, since package upgrades can happen at any time). The dialog doesn't check to see which Wine versions are available, it just lets you select them. If the script can't find the one you picked, it will just throw an error and ask you to try again.

Applications on Linux don't usually set environment variables like PATH. This is a good thing as it prevents process hijacking :)

Wine-staging is usually installed in `/opt` somewhere. If you add that to your PATH in `.bashrc` or whatever before `/usr/bin`, it will default to staging instead.

**Comment by alfonsojon** [comment]
This seems like a great idea; is it possible to make the "default" option more obvious? i.e. "If you're not sure, choose this", although that is not optimal.

**Comment by alfonsojon** [comment]
@GLolol Would you say this is ready to be merged?

**Comment by GLolol** [comment]
Ehh, I don't feel Wine Release Selection is super accurate either. What it really chooses is Wine path, and a different path doesn't necessarily mean that it's a different release being chosen - it just has to do with where things are being installed.

**Pull request merged**
