### PR TITLE
[needs discussion] Merge testing changes

### PR DESCRIPTION
**Pull request by GLolol**
A follow up for #68: So, I've done some testing and managed to iron out most of the bugs that #67 unfortunately created. This code is available in the [testing branch](https://github.com/alfonsojon/roblox-linux-wrapper/tree/testing).

However, the changes I've made now require the entire Git repository to be present, which changing the installation instructions by a bit. Thus, I want to discuss with @alfonsojon whether this is appropriate before merging anything myself.

Still to be tested:
- [ ] Upgrading from the current `rlw.sh` (in master) to the current testing code.

This pull request includes everything in #67 except for`-development` checking (reverted), and the following:
- Don't allow running as root.
- Firefox download now overwrites instead of creating a new file.
- **Parts of the script that relied on `~/.rlw` now install/run themselves in the directory RLW was cloned**. `roblox.desktop` is now automatically generated by the script to deal with ever-changing paths, and not shipped in the repository.

### CODE REVIEW

**Comment by alfonsojon** [comment]
While this seems great, the only thing I am not exactly a fan of are the changes to the installation mechanism. I understand this is probably more proper, but the average end user is confused enough by using a terminal, so telling them to run multiple git commands would seem difficult. Furthermore, the current directory (.rlw) is hidden, preventing the end user from accidentally uninstalling unless the installation is intentional.

Comment on line 159 ([[ -f "$HOME/.local/share/applications/roblox.desktop" ]] || {}), it should check for -x, as a "trusted" desktop file that has been properly installed should be marked as executable. Using the -x flag will check if it exists and is executable.

**Comment by GLolol** [comment]
@alfonsojon `.desktop` files do not need to be `+x`, that's completely unnecessary. I removed the `chmod` from the source because it doesn't really have any use.

**Comment by alfonsojon** [comment]
By the way, feel free to add yourself to the copyright notice. I may even remove the copyright, as there is no need (and goes against my beliefs)

**Comment by alfonsojon** [comment]
@GLolol The chmod part is indeed unnecessary; however, I was under the impression that .desktop files must be executable. When I had tried to run them without them being executable, the system either opened it in a text editor or asked if I'd like to "trust it", which would mark it as executable.

**Comment by alfonsojon** [comment]
@GLolol Can you test this by ```chmod -x /path/to/rlw.sh``` for me?

**Comment by GLolol** [comment]
.desktop files aren't actually ran directly IIRC. They are called via `xdg-open` when you run them from an applications menu.

**Comment by alfonsojon** [comment]
@GLolol Ah, I see. What does marking them as trusted do then? I'm not very familiar with the xdg-utils package, as I frequently use a CLI and X11 forwarding. Most of the coding I do is tested remotely, on a Linux server, with a X11 client on a Windows computer at school.

**Comment by GLolol** [comment]
Oh. The marking as trusted thing seems to be Ubuntu-specific... I don't know if a .desktop file in `~/.local/share/applications` can be ran without +x.

**Comment by alfonsojon** [comment]
@GLolol I use Ubuntu MATE 14.04 at home, so that would probably explain it. I don't believe it would hurt to check if it is executable, correct? xdg should automatically install it as executable by default anyways.

**Comment by GLolol** [comment]
Does it? Unfortunately, it doesn't seem that the `+x` is universal across all distros... None of the `.desktop` files in `/usr/share/applications` for me (Debian) are `+x`.

**Comment by alfonsojon** [comment]
This is a bit awkward. Should it be marked as executable only on Ubuntu systems?

**Comment by GLolol** [comment]
I just booted into a Ubuntu VM... Nothing in `~/.local/share/applications` seems to be `+x` either. Maybe those paths are whitelisted, I don't know.

**Comment by alfonsojon** [comment]
Perhaps we need a vendor?

**Comment by GLolol** [comment]
I don't know.

Also, The installation instructions can be merged into one command if you wish; just put them together with semicolons.

```
git clone https://github.com/alfonsojon/roblox-linux-wrapper;cd roblox-linux-wrapper;git checkout testing;./rlw.sh
```

The `git checkout testing` should be removed once this is merged to master.

**Comment by alfonsojon** [comment]
Yep, right now I'm cherry-picking stuff so that I can make the needed changes while implementing everything you added.

**Comment by GLolol** [comment]
Does git merge not work? It's usually better to conserve commit history to prevent even more conflicts from popping up... >_<

**Comment by alfonsojon** [comment]
Good point, I'll merge it once it's ready

**Comment by GLolol** [comment]
Honestly, I just don't like the idea of the script having to bootstrap a copy of *itself* in a separate folder. This is clunky and makes upgrading between big changes (like this one) really difficult.

**Comment by alfonsojon** [comment]
Good point. I still think the .desktop file should be cloned and not dynamically created, so that the file can be updated automatically if it changes on the git repo.

**Comment by alfonsojon** [comment]
I've changed the installation mechanism entirely - no more ```wrapper_install ()```, it is instead installed through a command (updated readme). I suggest you merge these changes into your repository, as to avoid conflicts.

**Comment by GLolol** [comment]
Where are the changes?

**Comment by alfonsojon** [comment]
In the master branch

**Comment by alfonsojon** [comment]
Now, there are conflicts currently, but that is because we both updated the .gitignore file, so it should be a relatively easy fix

**Comment by GLolol** [comment]
Well, 2914d28a1a83cd0ce089a705f0d2c24cdb015f3b removes all auto-updating entirely. Is git needed at all?

**Comment by alfonsojon** [comment]
@GLolol Yes, I'm adding the auto update to the main function if git is found and the current directory is a git repository.

**Comment by GLolol** [comment]
Updated. The difference between the two branches is now a lot smaller... Remaining changes:

* Fetching newest Firefox ESR build.
* Getting git branch dynamically.
* .desktop file is removed - master doesn't use it now, is this still needed?
* Remove `$WINEPREFIX` during uninstall.
* Don't allow running as root.
* Some few grammar/spelling fixes here and there.

**Comment by alfonsojon** [comment]
Wherever the script is ran, I believe the .desktop file should be there. The desktop file does not need to have a definite path, as it can be installed via a command and a relative path. This makes updating the desktop file easier, as the user does not have to reinstall it every time it changes, we can just update it and have the wrapper install the new desktop file.

**Comment by GLolol** [comment]
Doesn't xdg-desktop-menu make a copy of the `.desktop` file in `~/.local/share/applications`? How does it know when to upgrade then, if `rlw.sh` doesn't ever call it?

**Comment by alfonsojon** [comment]
Rather than dynamically generating it, it can just auto update via git, and can be installed at any time via the `xdg-desktop-menu install` command. Furthermore, I feel that a heredoc in a shell script to generate a `.desktop` file on the fly is a bit clunky, although that's more of a personal preference.

**Comment by alfonsojon** [comment]
@GLolol Some more changes from master should be merged into testing, as it takes care of some of the problems we've discussed, such as what we're doing about the .desktop file. The uninstallation mechanism has also been removed, in favor of manual removal.

**Comment by GLolol** [comment]
If you want a relative path to the `rlw.sh` file, it has to be in the user's $PATH.

The problem is: most DE's don't load custom $PATH's from `.bashrc` or whatever when they start a `.desktop` file.

**Comment by alfonsojon** [comment]
So, what are our options currently?

**Comment by GLolol** [comment]
I wrote a separate `gen-desktop.sh` to make `roblox.desktop`, but automating upgrades for it isn't possible without calling commands manually in `rlw.sh` (like, the installation clause).

As far as I'm concerned, automating upgrades for the .desktop file isn't even possible if we have a static dir. :|

`xdg-desktop-menu` stores everything in `~/.local/share/applications`. It doesn't care whether the original has changed or not.

**Comment by alfonsojon** [comment]
So basically, just make sure it doesn't need to be updated?

**Comment by GLolol** [comment]
Yeah. Frankly, it's a protocol limitation that's just there... Trying to work around it might be possible, but it'll be finicky and just plain.. *ugh*.

**Comment by alfonsojon** [comment]
Could we notify the user? We can have the wrapper have a manual, basic update function, and we can use md5 or shasum checking on the .desktop file. If the hash is different, we can notify the user of a .desktop file update.

**Comment by GLolol** [comment]
That sound fine. The script will call `gen-desktop.sh` on launch (it needs to find the current directory for that, though). I feel looking at the last modified date would be a lot less foolproof, in case anyone likes editing files themselves.

**Comment by GLolol** [comment]
(If gen-desktop is to be automatically called, we shouldn't need the spawndialog)

**Comment by alfonsojon** [comment]
ah, I thought it was manual. Alright

**Comment by alfonsojon** [comment]
@GLolol By the way, for portability, try to use "printf '%b\n" instead of echo, it's quicker (bash builtin) and more native. Echo is just used for the sake of backwards compatibility.

**Comment by GLolol** [comment]
I was originally making it manual, but the .desktop updating idea is fine with me. Is this merge-able where it is?

**Comment by alfonsojon** [comment]
With some testing, yes. I'll need to test the testing branch. Also, make sure to remove the branch-specific instructions, the more technical users can figure that out themselves :)

**Comment by GLolol** [comment]
The README was synced in the last merge, so there's nothing about `testing` in it.

I think a printf will be fine for both manual and automatic execution of `gen-desktop.sh`. Something simple like that shouldn't need zenity IMO.

**Comment by alfonsojon** [comment]
Alright. In the main instructions, for the uninstallation, I have it set to remove ./roblox-linux-wrapper, in the instance that the user has cloned in a location other than `$HOME`.

**Comment by GLolol** [comment]
Done.

**Comment by alfonsojon** [comment]
@GLolol Should rlw.sh force an installation if an already existing copy of roblox.desktop is found in `~/.local/share/applications/`?

**Comment by alfonsojon** [comment]
If we do that, then we can have it "update" automatically.

**Comment by GLolol** [comment]
I'm okay with that.

**Comment by alfonsojon** [comment]
Given how volatile the code in rlw is, it's probably a good idea anyways, as it's constantly changing.

**Comment by alfonsojon** [comment]
By the way, it says testing is behind master by one commit (?)

**Comment by GLolol** [comment]
I fixed the `rm -rf roblox-linux-wrapper` instructions. Don't worry about it, it doesn't cause conflicts.

It could just overwrite the .desktop file if it finds one. Otherwise, don't do anything?

**Comment by alfonsojon** [comment]
Yep, that's the plan. It will also not clobber the existing copy of roblox.desktop, so any user modifications are preserved.

**Comment by GLolol** [comment]
But, how will it know when to upgrade then?

**Comment by alfonsojon** [comment]
By that, I mean it will install the new copy if the following are met:
* File exists in `~/.local/share/applications
* File does not exist in `~/`

**Comment by GLolol** [comment]
I don't understand the second part.

**Comment by alfonsojon** [comment]
That will apply to all of our current users with the current roblox.desktop files. When the wrapper self-updates via git pull, it will automatically delete the local copy of roblox.desktop from the local repo

**Comment by alfonsojon** [comment]
meaning the local repo (`~/`) lacks the desktop file, so we can generate it. If the user modified it, it'll stay there, untouched. Git doesn't clobber, and neither will the wrapper.

**Comment by GLolol** [comment]
I don't think git automatically deletes untracked files. It can just overwrite the roblox.desktop in the RLW source folder even if it exists, it doesn't matter.

**Comment by alfonsojon** [comment]
Alright, I thought git did. Either way, that's not too big of a deal anyways, as the user could just modify the gen-desktop.sh script if they really wanted to mod the desktop file.

**Comment by GLolol** [comment]
Indeed.

**Comment by autospamfighter** [comment]
Couldn't you add in a "git clean -f -X"?

**Comment by alfonsojon** [comment]
Did you commit gen-desktop.sh as executable?

**Comment by GLolol** [comment]
@alfonsojon Yes.

**Comment by alfonsojon** [comment]
@GLolol Perfect, so the check if executable check should be fine. I've committed the changes necessary to make the script install the .desktop file.

**Comment by GLolol** [comment]
???

`gen-desktop.sh` is +x, roblox.desktop isn't.

**Comment by alfonsojon** [comment]
Yes, that's what's being checked.
```
printf '%b\n' " > begin main ()\n---"
[[ -x "gen-desktop.sh" ]] && {
	gen-desktop.sh
	spawndialog question "Would you like to install the Roblox menu item on your system?"
	[[ "$?" = "0" ]] && {
		xdg-desktop-menu install --novendor --mode user roblox.desktop
	}
}
```

**Comment by alfonsojon** [comment]
Ready for merge?

**Comment by GLolol** [comment]
Yup.

**Comment by alfonsojon** [comment]
@autospamfighter Why?

**Comment by GLolol** [comment]
I recommend not deleting the testing branch after merge. This allows us (and others) to stage more changes here in the future. :)

**Comment by alfonsojon** [comment]
@GLolol Got it :+1:

**Comment by martywd** [comment]
Apologies IA if this is wrong place to add this???

Did another 'git clone...', renamed 'roblox-linux-wrapper' directory to '.rlw' just to be contrary AND I don't need more visible directories in my profile.  Then ran './rlw.sh'.  All seems to go well except for multiple prompts for 'Would you like to install the Roblox menu item on your system' which continually fails.  This is latest error, the others were similar:

`marty@triton ~/.rlw`
`$ ./rlw.sh`
`Roblox Linux Wrapper v20150412-master`
`Already up-to-date.`
`---`
`./rlw.sh: line 162: gen-desktop.sh: command not found`
`xdg-desktop-menu: file 'roblox.desktop' does not exist`
``
`---`

OT:  Sorry, 'Markdown' is a bit confusing so I deleted the lines beginning with ">" in the above error report because it all 'looked' a bit weird in 'Preview'.
.

**Comment by alfonsojon** [comment]
Try using a triple ` around your code, like so.
```
This is multi-line code!
Hello!
```

**Comment by alfonsojon** [comment]
@martywd I'll try to fix that shortly.

**Comment by alfonsojon** [comment]
@martywd See bug #73.

**Comment by GLolol** [comment]
Should be fixed now.

**Pull request merged**
